name: Security

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 12 1 * *'

jobs:
  vuln-scan:
    runs-on: ubuntu-latest
    container:
      image: golang:1.25-alpine
    steps:
    - uses: actions/checkout@v4
    
    - name: Install govulncheck
      run: go install golang.org/x/vuln/cmd/govulncheck@latest
    
    - name: Download dependencies
      run: go mod download
    
    - name: Run vulnerability scan
      run: govulncheck ./...
  
  staticcheck:
    runs-on: ubuntu-latest
    container:
      image: golang:1.25-alpine
    steps:
    - uses: actions/checkout@v4
    
    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest
    
    - name: Download dependencies
      run: go mod download
    
    - name: Run static analysis
      run: staticcheck ./...