name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: golang:1.25-alpine
    steps:
    - uses: actions/checkout@v4
    
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: /go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    
    - name: Download dependencies
      run: go mod download
    
    - name: Run tests
      run: go test -cover ./...
    
    - name: Vet code
      run: go vet ./...
    
    - name: Format check
      run: |
        go fmt ./...
        if [ -n "$(git diff --name-only)" ]; then
          echo "Code is not formatted. Run 'go fmt ./...'"
          exit 1
        fi
    
    - name: Build
      run: go build -ldflags="-s -w" -o padecer .